name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Create .env file from GitHub Secrets
        run: |
          echo "VITE_API_SUPABASE=${{ secrets.VITE_API_SUPABASE }}" >> .env
          echo "VITE_API_SUPABASE_KEY=${{ secrets.VITE_API_SUPABASE_KEY }}" >> .env
          echo "VITE_DEFAULT_TIMEOUT=${{ secrets.VITE_DEFAULT_TIMEOUT }}" >> .env

      - name: Build
        run: pnpm build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
